# Generated by Django 4.2.16 on 2026-05-27 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('subject', models.CharField(choices=[('chemistry', 'Химия'), ('biology', 'Биология'), ('math', 'Математика'), ('history', 'История'), ('russian', 'Русский язык')], max_length=20, verbose_name='Предмет')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='easy', max_length=10, verbose_name='Сложность')),
                ('time_limit', models.PositiveIntegerField(default=10, verbose_name='Время (мин)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('option_a', models.CharField(max_length=400, verbose_name='Вариант A')),
                ('option_b', models.CharField(max_length=400, verbose_name='Вариант B')),
                ('option_c', models.CharField(max_length=400, verbose_name='Вариант C')),
                ('option_d', models.CharField(max_length=400, verbose_name='Вариант D')),
                ('correct', models.PositiveSmallIntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')], verbose_name='Правильный ответ')),
                ('explanation', models.TextField(blank=True, verbose_name='Объяснение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['created_at'],
            },
        ),
    ]
